# Generated by Django 5.1.3 on 2024-11-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_telefone',
            field=models.IntegerField(),
        ),
    ]
