# Generated by Django 5.1.3 on 2024-11-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cliente_numero_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='numero_telefone',
            new_name='telefone',
        ),
    ]
