# Generated by Django 5.1.3 on 2024-11-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
    ]
