# Generated by Django 5.1.3 on 2024-11-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mensagem_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='status',
            field=models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], default='success', max_length=10),
        ),
    ]
