# Generated by Django 5.1.3 on 2024-11-30 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mensagem_resposta_mensagem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='usuario',
        ),
        migrations.CreateModel(
            name='EnviarMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mensagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
    ]
