# Generated by Django 5.1.3 on 2024-11-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_mensagem_usuario_enviarmensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='status',
        ),
        migrations.AddField(
            model_name='enviarmensagem',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviarmensagem',
            name='status',
            field=models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], default='success', max_length=10),
        ),
    ]
